### ISSUE TITLE
Windows Implementation

### ISSUE THREAD

**Issue by WindowsNT** [itzmeanjan/kyber#36]
I just implemented the Kyber algorithsm into my CNG implementation (https://github.com/WindowsNT/sha3cng) so Windows user can use them with CNG.

I had to remove some consteval/constexpr from the files and also there's a greek ζ not recognized in Visual Studio 2022.

Congratulations for your work.

**Comment by WindowsNT** [comment]
Edit: I resaved all files to "Unicode" instead of the "Unicode without BOM" , that fixed the greek letter problems (I'm greek myself :)).

Also, there is some bug that all the libraries cannot reside in the same static library, the Kyber algorithm has errors.
Perhaps you could make some namespace version.

**Comment by itzmeanjan** [comment]
> Edit: I resaved all files to "Unicode" instead of the "Unicode without BOM" , that fixed the greek letter problems (I'm greek myself :)).

Cool. Good to know that. 

> Also, there is some bug that all the libraries cannot reside in the same static library, the Kyber algorithm has errors.
I'm not following, do you have some sort of error log ?

> Perhaps you could make some namespace version.

I see, an example may be ?

**Comment by itzmeanjan** [comment]
As I didn't receive any response back, I'm closing this issue for now. Please feel free to open, in case that's required.
